# Generated by Django 5.2 on 2026-02-03 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrailArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trail_Distance', models.CharField(help_text='Trail Mileage', max_length=100)),
                ('Trail_Name', models.CharField(help_text='Trail Name', max_length=200)),
                ('Trail_Location', models.CharField(help_text='Trail Location Name', max_length=200)),
                ('Author', models.CharField(help_text='Your First and Last Names', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title e.g. NCMTB.com/url-friendly-slug', unique=True)),
                ('Trail_Difficulty_Range', models.CharField(help_text='Enter difficulty range', max_length=20)),
                ('Main_Features_Trails', models.TextField(blank=True, help_text='Enter the main trails and features at location e.g. Mountain Creek Hub, Loop, Jumps, Pump Track.', null=True)),
                ('trail_short_card_description', models.TextField(blank=True, help_text='Short trail description for cards', null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('Title_Trail_Image', models.ImageField(blank=True, upload_to='trail_photos')),
                ('Trail_Map_Image', models.ImageField(blank=True, upload_to='trail_photos')),
                ('Trail_Introduction_Description', models.TextField(blank=True, help_text='Introductory description of the trail.')),
                ('Trail_Video_Short', models.URLField(blank=True, help_text='Optional Short YouTube Video', null=True)),
                ('Trail_Video_Long', models.URLField(blank=True, help_text='Optional Long YouTube Video', null=True)),
                ('First_Trail_Section_Image', models.ImageField(blank=True, help_text='1st Trail/Section Leading Image', upload_to='trail_photos')),
                ('First_Trail_Section_Title', models.CharField(help_text='Sub-trail name', max_length=100)),
                ('First_Trail_Section_Difficulty', models.CharField(help_text='Sub-trail difficulty', max_length=20)),
                ('First_Trail_Section_Distance', models.CharField(help_text='Sub-trail distance', max_length=20)),
                ('First_Trail_Section_Desc', models.TextField(blank=True, help_text='1st Trail/Section Description')),
                ('Second_Trail_Section_Image', models.ImageField(blank=True, help_text='2nd Trail/Section Leading Image', upload_to='trail_photos')),
                ('Second_Trail_Section_Title', models.CharField(help_text='Sub-trail name', max_length=100)),
                ('Second_Trail_Section_Difficulty', models.CharField(help_text='Sub-trail difficulty', max_length=20)),
                ('Second_Trail_Section_Distance', models.CharField(help_text='Sub-trail distance', max_length=20)),
                ('Second_Trail_Section_Desc', models.TextField(blank=True, help_text='2nd Trail/Section Description')),
                ('Third_Trail_Section_Image', models.ImageField(blank=True, help_text='3rd Trail/Section Leading Image', upload_to='trail_photos')),
                ('Third_Trail_Section_Title', models.CharField(help_text='Sub-trail name', max_length=100)),
                ('Third_Trail_Section_Difficulty', models.CharField(help_text='Sub-trail difficulty', max_length=20)),
                ('Third_Trail_Section_Distance', models.CharField(help_text='Sub-trail distance', max_length=20)),
                ('Third_Trail_Section_Desc', models.TextField(blank=True, help_text='3rd Trail/Section Description')),
            ],
            options={
                'verbose_name': 'Trail Article',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='NCMTB.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='NCMTB.trailarticle')),
            ],
        ),
    ]
