# Generated by Django 5.2 on 2026-02-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
