# Generated by Django 5.2 on 2026-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0002_trailarticle_latitude_trailarticle_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Trail_Address',
            field=models.CharField(blank=True, help_text="For Google Maps API... Street address or 'Park Name, City, State'", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='1st Trail/Section Description', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Difficulty',
            field=models.CharField(help_text='Sub-trail difficulty', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Distance',
            field=models.CharField(help_text='Sub-trail distance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='1st Trail/Section Leading Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Title',
            field=models.CharField(help_text='Sub-trail name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='For weather API... Use maps.ie/coordinates.html to find coordinates.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='For weather API... Use maps.ie/coordinates.html to find coordinates.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='2nd Trail/Section Description', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Difficulty',
            field=models.CharField(help_text='Sub-trail difficulty', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Distance',
            field=models.CharField(help_text='Sub-trail distance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='2nd Trail/Section Leading Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Title',
            field=models.CharField(help_text='Sub-trail name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='3rd Trail/Section Description', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Difficulty',
            field=models.CharField(help_text='Sub-trail difficulty', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Distance',
            field=models.CharField(help_text='Sub-trail distance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='3rd Trail/Section Leading Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Title',
            field=models.CharField(help_text='Sub-trail name', max_length=100, null=True),
        ),
    ]
