# Generated by Django 5.2 on 2026-02-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0003_trailarticle_trail_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Location',
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Maintained_By',
            field=models.CharField(blank=True, help_text='Justin to add Tarheel and other auto logo image SVGs.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Trail_Tags',
            field=models.CharField(blank=True, help_text='Justin to add MANY TO MANY Model relationship for tag selection.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='e_bikes_allowed',
            field=models.CharField(blank=True, help_text='Yes or No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='For weather API and Google Maps API... goto Google Maps, drop pin at location, right-click and copy coords..', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='For weather API and Google Maps API... goto Google Maps, drop pin at location, right-click and copy coords..', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Address',
            field=models.CharField(blank=True, help_text="Physical address to show on page.'", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Difficulty_Range',
            field=models.CharField(help_text='Enter difficulty range', max_length=50),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Name',
            field=models.CharField(help_text='Trail Location Name', max_length=200),
        ),
    ]
