# Generated by Django 5.2 on 2026-02-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0004_remove_trailarticle_trail_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Video_Long',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Video_Short',
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
    ]
