# Generated by Django 5.2 on 2026-02-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0005_remove_trailarticle_trail_video_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailarticle',
            old_name='Trail_Video',
            new_name='Overview_Trail_Video',
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='First_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Second_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Third_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
    ]
