# Generated by Django 6.0.1 on 2026-03-09 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0006_rename_trail_video_trailarticle_overview_trail_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='Author',
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Trail_Landing_Desc',
            field=models.CharField(default=django.utils.timezone.now, help_text='Landing Page Description', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Distance',
            field=models.CharField(help_text='Total Trail Mileage', max_length=100),
        ),
    ]
