# Generated by Django 6.0.1 on 2026-03-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0007_remove_trailarticle_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Trail_Card_Logo',
            field=models.ImageField(blank=True, help_text='Image that shows up on card on landing. Typically a trail logo ex: Airline Logo.', null=True, upload_to='trail_photos'),
        ),
    ]
