# Generated by Django 6.0.1 on 2026-03-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0008_trailarticle_trail_card_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Eigth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Eigth_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Eigth_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Eigth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Eigth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Eigth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fifth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fifth_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fifth_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fifth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fifth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fifth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fourth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fourth_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fourth_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fourth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fourth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fourth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Ninth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Ninth_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Ninth_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Ninth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Ninth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Ninth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Seventh_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Seventh_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Seventh_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Seventh_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Seventh_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Seventh_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Sixth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Sixth_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Sixth_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Sixth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Sixth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Sixth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Tenth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Tenth_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Tenth_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Tenth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Tenth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Tenth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='First_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Main_Features_Trails',
            field=models.TextField(blank=True, help_text='Enter the main trails and features on individual line e.g. Mountain Creek Hub, Loop, Jumps, Pump Track. Each line will be a bulleted list.', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Maintained_By',
            field=models.CharField(blank=True, help_text='Who owns/maintains the trail.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Overview_Trail_Video',
            field=models.TextField(blank=True, help_text='Overview video of the trails at the location. This is a YouTube Embed Code.', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Second_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Difficulty',
            field=models.CharField(blank=True, help_text='Trail Difficulty', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Distance',
            field=models.CharField(blank=True, help_text='Trail Distance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Third_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Title_Trail_Image',
            field=models.ImageField(blank=True, help_text='This image appears on the Trail page as an opening image. This should be an action shot and eye-catcher e.g. Flight Deck at Airline.', upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Address',
            field=models.CharField(blank=True, help_text="Physical address of the trail to show on page.'", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Card_Logo',
            field=models.ImageField(blank=True, help_text='Image that shows up on card on landing page tile. Typically a trail logo ex: Airline Logo.', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Difficulty_Range',
            field=models.CharField(help_text='Enter the range of difficulty at the trail e.g. Green-Black.', max_length=50),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Distance',
            field=models.CharField(help_text='Total Trail Mileage including all trails and also lead with a tilda (~) e.g. ~26 Miles', max_length=100),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Introduction_Description',
            field=models.TextField(blank=True, help_text='Skip for now. Need to remove.'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Landing_Desc',
            field=models.CharField(help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=500),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Map_Image',
            field=models.ImageField(blank=True, help_text='The trail map is displayed on the trail page under Trails tab.', upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Name',
            field=models.CharField(help_text='Trail Location Name e.g. Whitewater Center', max_length=200),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Tags',
            field=models.CharField(blank=True, help_text='We will go back and add these possibly. Its a way to add metadata on the trail so that we can add categories and sorting later.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='trail_short_card_description',
            field=models.TextField(blank=True, help_text='Add individual lines about key features that will show up on the card as a bulleted list (for each separate line).', null=True),
        ),
    ]
