# Generated by Django 6.0.1 on 2026-03-13 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0009_trailarticle_eigth_trail_section_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Trail_Website',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Title_Trail_Image',
            field=models.ImageField(help_text='This image appears on the Trail page as an opening image. This should be an action shot and eye-catcher e.g. Flight Deck at Airline.', upload_to='trail_photos'),
        ),
    ]
