# Generated by Django 6.0.1 on 2026-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0010_trailarticle_trail_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Order_Priority',
            field=models.CharField(default=1, help_text='Priority of Trail that dictates where it is displayed on the home screen. 1 being first, etc.', max_length=10),
            preserve_default=False,
        ),
    ]
