# Generated by Django 6.0.1 on 2026-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0011_trailarticle_order_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailarticle',
            options={'ordering': ['Order_Priority'], 'verbose_name': 'Trail Article'},
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Order_Priority',
            field=models.IntegerField(help_text='Priority of Trail that dictates where it is displayed on the home screen. 1 being first, etc.', max_length=10),
        ),
    ]
