# Generated by Django 6.0.1 on 2026-03-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0012_alter_trailarticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Eigth_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fifth_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='First_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Fourth_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Ninth_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Second_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Seventh_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Sixth_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Tenth_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Third_Trail_Short',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Order_Priority',
            field=models.IntegerField(help_text='Priority of Trail that dictates where it is displayed on the home screen. 1 being first, etc.'),
        ),
    ]
