# Generated by Django 6.0.1 on 2026-04-07 13:06

import django.utils.timezone
import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0013_trailarticle_eigth_trail_short_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='Maintained_By',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Difficulty_Range',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Introduction_Description',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Tags',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='e_bikes_allowed',
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Trail_MD_Desc',
            field=markdownfield.models.MarkdownField(default=django.utils.timezone.now, rendered_field='text_rendered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Trail_MD_Desc_Rendered',
            field=markdownfield.models.RenderedMarkdownField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
