# Generated by Django 6.0.1 on 2026-04-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0013_trailarticle_eigth_trail_short_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='Maintained_By',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Difficulty_Range',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Introduction_Description',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Tags',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='e_bikes_allowed',
        ),
    ]
