# Generated by Django 6.0.1 on 2026-04-07 13:16

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0014_remove_trailarticle_maintained_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_MD_Desc',
            field=markdownfield.models.MarkdownField(rendered_field='Trail_MD_Desc_Rendered'),
        ),
    ]
