# Generated by Django 6.0.1 on 2026-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0014_remove_trailarticle_maintained_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Feature_Spotlight_1',
            field=models.ImageField(help_text='This image is a feature spotlight.', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Feature_Spotlight_1_Desc',
            field=models.CharField(help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Feature_Spotlight_2',
            field=models.ImageField(help_text='This image is a feature spotlight.', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Feature_Spotlight_2_Desc',
            field=models.CharField(help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Feature_Spotlight_3',
            field=models.ImageField(help_text='This image is a feature spotlight.', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Feature_Spotlight_3_Desc',
            field=models.CharField(help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Feature_Spotlight_4',
            field=models.ImageField(help_text='This image is a feature spotlight.', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Feature_Spotlight_4_Desc',
            field=models.CharField(help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=500, null=True),
        ),
    ]
