# Generated by Django 6.0.1 on 2026-04-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0015_trailarticle_feature_spotlight_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='Overview_Trail_Video',
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Feature_Spotlight_1',
            field=models.ImageField(blank=True, help_text='This image is a feature spotlight.', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Feature_Spotlight_1_Desc',
            field=models.CharField(blank=True, help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Feature_Spotlight_2',
            field=models.ImageField(blank=True, help_text='This image is a feature spotlight.', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Feature_Spotlight_2_Desc',
            field=models.CharField(blank=True, help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Feature_Spotlight_3',
            field=models.ImageField(blank=True, help_text='This image is a feature spotlight.', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Feature_Spotlight_3_Desc',
            field=models.CharField(blank=True, help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Feature_Spotlight_4',
            field=models.ImageField(blank=True, help_text='This image is a feature spotlight.', null=True, upload_to='trail_photos'),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Feature_Spotlight_4_Desc',
            field=models.CharField(blank=True, help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=500, null=True),
        ),
    ]
