# Generated by Django 6.0.1 on 2026-04-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0016_remove_trailarticle_overview_trail_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='Title_Trail_Image',
        ),
    ]
