# Generated by Django 6.0.1 on 2026-04-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0017_remove_trailarticle_title_trail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Approach_img_1',
            field=models.ImageField(blank=True, help_text='This image is an approach to the trail head.', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Approach_img_1_Desc',
            field=models.CharField(blank=True, help_text='Trailhead approach description.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Approach_img_2',
            field=models.ImageField(blank=True, help_text='This image is an approach to the trail head.', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Approach_img_2_Desc',
            field=models.CharField(blank=True, help_text='Trailhead approach description.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Approach_img_3',
            field=models.ImageField(blank=True, help_text='This image is an approach to the trail head.', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Approach_img_3_Desc',
            field=models.CharField(blank=True, help_text='Trailhead approach description.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Approach_img_4',
            field=models.ImageField(blank=True, help_text='This image is an approach to the trail head.', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Approach_img_4_Desc',
            field=models.CharField(blank=True, help_text='Trailhead approach description.', max_length=500, null=True),
        ),
    ]
