# Generated by Django 6.0.1 on 2026-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0018_trailarticle_approach_img_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Beginner_Priority',
            field=models.IntegerField(blank=True, help_text="Priority of Trail that dictates whether it's beginner friendly.", null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Bike_Park_Priority',
            field=models.IntegerField(blank=True, help_text='Priority of Trail that dictates whether its a bike park.', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Loc_Priority',
            field=models.IntegerField(blank=True, help_text='Priority of Trail that dictates where it is displayed on the home screen. 1 being first, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Order_Priority',
            field=models.IntegerField(blank=True, help_text='Priority of Trail that dictates where it is displayed on the home screen. 1 being first, etc.', null=True),
        ),
    ]
