# Generated by Django 6.0.1 on 2026-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0019_trailarticle_beginner_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='Eigth_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Eigth_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Eigth_Trail_Short',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Fifth_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Fifth_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Fifth_Trail_Short',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='First_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='First_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='First_Trail_Short',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Fourth_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Fourth_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Fourth_Trail_Short',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Ninth_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Ninth_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Ninth_Trail_Short',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Second_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Second_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Second_Trail_Short',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Seventh_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Seventh_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Seventh_Trail_Short',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Sixth_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Sixth_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Sixth_Trail_Short',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Tenth_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Tenth_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Tenth_Trail_Short',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Third_Trail_Section_Difficulty',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Third_Trail_Section_Distance',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Third_Trail_Short',
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Eleventh_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Eleventh_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Eleventh_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Eleventh_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Twelfth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Twelfth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Twelfth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Twelfth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
    ]
