# Generated by Django 6.0.1 on 2026-04-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0020_remove_trailarticle_eigth_trail_section_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='date_updated',
        ),
    ]
