# Generated by Django 6.0.1 on 2026-04-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0021_remove_trailarticle_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='Family_Priority',
            field=models.IntegerField(blank=True, help_text="Priority of Trail that dictates whether it's beginner friendly.", null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Map_Image',
            field=models.ImageField(blank=True, help_text='The trail map is displayed on the trail page under Trails tab.', null=True, upload_to='trail_photos'),
        ),
    ]
