# Generated by Django 6.0.1 on 2026-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0022_trailarticle_family_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(help_text='Trail Location Name e.g. Whitewater Center', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title e.g. NCMTB.com/blog-post-title', unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('Lead_Image', models.ImageField(blank=True, help_text='Eye catcher.', null=True, upload_to='trail_photos')),
                ('Intro_Text', models.CharField(help_text='Intro statement.', max_length=500)),
                ('Sect_1_Image', models.ImageField(blank=True, help_text='Section 1 lead photo', null=True, upload_to='trail_photos')),
                ('Sect_1_Text', models.CharField(help_text='First section.', max_length=500)),
                ('Sect_2_Image', models.ImageField(blank=True, help_text='Section 1 lead photo', null=True, upload_to='trail_photos')),
                ('Sect_2_Text', models.CharField(help_text='First section.', max_length=500)),
                ('Sect_3_Image', models.ImageField(blank=True, help_text='Section 1 lead photo', null=True, upload_to='trail_photos')),
                ('Sect_3_Text', models.CharField(help_text='First section.', max_length=500)),
                ('Sect_4_Image', models.ImageField(blank=True, help_text='Section 1 lead photo', null=True, upload_to='trail_photos')),
                ('Sect_4_Text', models.CharField(help_text='First section.', max_length=500)),
                ('Sect_5_Image', models.ImageField(blank=True, help_text='Section 1 lead photo', null=True, upload_to='trail_photos')),
                ('Sect_5_Text', models.CharField(help_text='First section.', max_length=500)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Know_Before',
            field=models.CharField(blank=True, help_text='Know before you go.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='Trail_Vibe',
            field=models.CharField(blank=True, help_text='Trail Vibe.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Card_Logo',
            field=models.ImageField(blank=True, help_text='Width must be 350 px.', null=True, upload_to='trail_photos'),
        ),
    ]
