# Generated by Django 6.0.1 on 2026-04-30 14:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0023_blog_trailarticle_know_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Intro_Text',
            field=ckeditor.fields.RichTextField(help_text='Intro statement.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Sect_1_Text',
            field=ckeditor.fields.RichTextField(help_text='First section.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Sect_2_Text',
            field=ckeditor.fields.RichTextField(help_text='First section.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Sect_3_Text',
            field=ckeditor.fields.RichTextField(help_text='First section.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Sect_4_Text',
            field=ckeditor.fields.RichTextField(help_text='First section.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Sect_5_Text',
            field=ckeditor.fields.RichTextField(help_text='First section.', max_length=500),
        ),
    ]
