# Generated by Django 6.0.1 on 2026-04-30 14:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0024_alter_blog_intro_text_alter_blog_sect_1_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Sect_1_Image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Sect_1_Text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Sect_2_Image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Sect_2_Text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Sect_3_Image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Sect_3_Text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Sect_4_Image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Sect_4_Text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Sect_5_Image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Sect_5_Text',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Intro_Text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Intro statement.', max_length=500),
        ),
    ]
