# Generated by Django 6.0.1 on 2026-05-04 17:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0025_remove_blog_sect_1_image_remove_blog_sect_1_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailarticle',
            name='Know_Before',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Main_Features_Trails',
        ),
        migrations.RemoveField(
            model_name='trailarticle',
            name='Trail_Vibe',
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Landing_Desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Trail Description that appears on the Trail page as an opening statement.', max_length=1000),
        ),
    ]
