# Generated by Django 6.0.1 on 2026-05-04 17:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0027_alter_trailarticle_trail_landing_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailarticle',
            name='Trail_Landing_Desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Trail Description that appears on the Trail page as an opening statement.', null=True),
        ),
        migrations.AlterField(
            model_name='trailarticle',
            name='trail_short_card_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Add individual lines about key features that will show up on the card as a bulleted list (for each separate line).', null=True),
        ),
    ]
