# Generated by Django 6.0.1 on 2026-05-08 17:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0028_alter_trailarticle_trail_landing_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_Body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Blog body.', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Blog_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Intro_Text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Intro paragraph.'),
        ),
    ]
