# Generated by Django 6.0.1 on 2026-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0029_blog_blog_body_blog_blog_video_alter_blog_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_Title',
            field=models.CharField(help_text='Trail Location Name e.g. Whitewater Center'),
        ),
    ]
