# Generated by Django 6.0.1 on 2026-05-20 13:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0030_alter_blog_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='back_card_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Top Line Tags (3-4), Second Line Difficulty and Mileage', null=True),
        ),
    ]
