# Generated by Django 6.0.1 on 2026-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0031_trailarticle_back_card_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Title_img',
            field=models.ImageField(blank=True, help_text='Blog Title Image eye catcher.', null=True, upload_to='trail_photos'),
        ),
    ]
