# Generated by Django 6.0.1 on 2026-06-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0032_blog_title_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='trailforks_region_id',
            field=models.IntegerField(blank=True, help_text='Trailforks Region ID (e.g., 45965)', null=True),
        ),
    ]
