# Generated by Django 6.0.1 on 2026-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0033_trailarticle_trailforks_region_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='eighteenth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='eighteenth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='eighteenth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='eighteenth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='fifteenth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='fifteenth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='fifteenth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='fifteenth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='fourteenth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='fourteenth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='fourteenth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='fourteenth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='ninteenth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='ninteenth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='ninteenth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='ninteenth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='seventeenth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='seventeenth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='seventeenth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='seventeenth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='sixteenth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='sixteenth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='sixteenth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='sixteenth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='thirteenth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='thirteenth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='thirteenth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='thirteenth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentieth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentieth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentieth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentieth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
    ]
