# Generated by Django 6.0.1 on 2026-09-01 00:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0034_trailarticle_eighteenth_trail_section_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Intro_Text_Home',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Very short intro for home page display.', null=True),
        ),
    ]
