# Generated by Django 6.0.1 on 2026-09-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0035_blog_intro_text_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='city_state',
            field=models.CharField(blank=True, help_text='City and State of Trail e.g. Charlotte, NC', max_length=100, null=True),
        ),
    ]
