# Generated by Django 6.0.1 on 2026-09-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCMTB', '0036_trailarticle_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailarticle',
            name='thirtieth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='thirtieth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='thirtieth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='thirtieth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyeighth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyeighth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyeighth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyeighth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfifth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfifth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfifth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfifth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfirst_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfirst_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfirst_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfirst_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfourth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfourth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfourth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyfourth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyninth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyninth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyninth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyninth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentysecond_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentysecond_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentysecond_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentysecond_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyseventh_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyseventh_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyseventh_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentyseventh_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentysixth_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentysixth_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentysixth_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentysixth_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentythird_Trail_Section_Desc',
            field=models.TextField(blank=True, help_text='Trail Description', null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentythird_Trail_Section_Image',
            field=models.ImageField(blank=True, help_text='Trail Image', null=True, upload_to='trail_photos'),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentythird_Trail_Section_Title',
            field=models.CharField(blank=True, help_text='Trail Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trailarticle',
            name='twentythird_Trail_Video',
            field=models.TextField(blank=True, help_text='YouTube Embed Code', null=True),
        ),
    ]
