"""
Django settings for DevWriter_Umbrella project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Look for a secret key in the environment; if not found, use a 'dummy' string
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-dev-key-123')

# Also, ensure DEBUG is True locally so you can see errors
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'



# Set the project base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(DEBUG=(bool, False))

# Read the .env file (using the new Path object logic)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))



ALLOWED_HOSTS = ['url', 'www url', 'ip', 'localhost', '127.0.0.1', '174.138.66.218', 'charlottencmtb.com', 'www.charlottencmtb.com', 'www.ridecltmtb.com', 'ridecltmtb.com']


# Application definition

INSTALLED_APPS = [
    
    # Admin Portal Styling
    'jazzmin',
    
     # My Apps 
    'NCMTB',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DevWriter_Umbrella.urls'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#API Keys
OPENWEATHER_API_KEY = env('OPENWEATHER_API_KEY')
GOOGLE_MAPS_API_KEY = env('GOOGLE_MAPS_API_KEY')


WSGI_APPLICATION = 'DevWriter_Umbrella.wsgi.application'

# Default auto field tells Django to use 64-bit integer IDs (the standard) for auto-generated ID numbers for rows in the DB.

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


BASE_DIR = Path(__file__).resolve().parent.parent

# This is the URL used to access static files in the browser
STATIC_URL = 'static/'

# This is where collectstatic will put your files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 






# The absolute filesystem path to the directory that will hold user-uploaded files

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 