"""
Django settings for DevWriter_Umbrella project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# ------------------------------------------------------------------------------
# 1. BASE DIRECTORY & ENV SETUP
# ------------------------------------------------------------------------------
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    DEBUG=(bool, True)
)

# Read the .env file if it exists at project root
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(str(env_file))

# ------------------------------------------------------------------------------
# 2. SECURITY & CORE SETTINGS
# ------------------------------------------------------------------------------
SECRET_KEY = env('SECRET_KEY', default='django-insecure-local-dev-key-123')

DEBUG = env.bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = [
    'url', 
    'www url', 
    'ip', 
    'localhost', 
    '127.0.0.1', 
    '174.138.66.218', 
    'charlottencmtb.com', 
    'www.charlottencmtb.com', 
    'www.ridecltmtb.com', 
    'ridecltmtb.com', 
    'charlottemtb.com', 
    'www.charlottemtb.com',
]

# ------------------------------------------------------------------------------
# 3. APPLICATION DEFINITION
# ------------------------------------------------------------------------------
INSTALLED_APPS = [
    'NCMTB',

    # Admin Portal Styling
    'jazzmin',

    # Img Handling
    'imagekit',

    # WYSIWYG Editor
    'ckeditor',
    'ckeditor_uploader',

    # Default Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DevWriter_Umbrella.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DevWriter_Umbrella.wsgi.application'

# ------------------------------------------------------------------------------
# 4. API KEYS
# ------------------------------------------------------------------------------
OPENWEATHER_API_KEY = env('OPENWEATHER_API_KEY', default='')
GOOGLE_MAPS_API_KEY = env('GOOGLE_MAPS_API_KEY', default='')

# ------------------------------------------------------------------------------
# 5. DATABASE
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------------------------
# 6. PASSWORD VALIDATION
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ------------------------------------------------------------------------------
# 7. INTERNATIONALIZATION
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# ------------------------------------------------------------------------------
# 8. STATIC & MEDIA FILES
# ------------------------------------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CKEDITOR_UPLOAD_PATH = "uploads/"

# ------------------------------------------------------------------------------
# 9. THIRD-PARTY APP CONFIGURATIONS
# ------------------------------------------------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "CharlotteMTB Admin Portal",
    "site_header": "CharlotteMTB Admin Portal",
    "welcome_sign": "Welcome to the CharlotteMTB Admin Portal",
    
    # Adds the Tech Stack to the top navigation bar
    "topmenu_links": [
        {"name": "Home",  "url": "control_center:index"},
        {"name": "Tech Stack", "url": "control_center:tech_stack"},
    ],

    # Ensures the sidebar is always open and easy to navigate
    "show_sidebar": True,
    "navigation_expanded": True,
}